apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
        - name: product-catalogue
          image: 975049965288.dkr.ecr.us-east-1.amazonaws.com/commerce-internal-assigment2:productcatalogue
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service
spec:
  selector:
    app: product-catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer