apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalogue80
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-catalogue
  template:
    metadata:
      labels:
        app: product-catalogue
    spec:
      containers:
        - name: product-catalogue
          image: 730335419891.dkr.ecr.us-east-2.amazonaws.com/common-internal-assignment:product-catalogue-service
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service80
spec:
  selector:
    app: product-catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer