server:
  port: 8071

spring:
  application:
  name: "configserver"
  profiles:
   active: native
  cloud:
    config:
      server:
        native:
          search-locaitons: "classpath:/config"


#encrypt:
#  key: "ABCDEF973893"
